# Level4
# Colors:
# X Black
# Background:
# R Red

grid = [
"R               ",
"       @@       ",
"                ",
"                ",
"                ",
"                ",
"...........    m",
"XXXXXXXXXXX-----",
"       X        ",
"       X   f    ",
"ZZZ^ZZZX        ",
" . X  <X--------",
" . X   X        ",
" . X>  Xm       ",
" . X   X--------",
" . X  <X        ",
" . X   X       m",
" . X>  X--------",
" . X            ",
" . X            ",
"ZZZXNNNNNNNNNNNN",
"                ",
"  ..            ",
"  bb   ..       ",
"       bb  ..   ",
"           bb   ",
"                ",
"   NN  NN   NNNN",
"                ",
"                ",
"B ^^..^^..^^    ",
"XXXXXXXXXXXXX...",
"                ",
"                ",
"....NNNN.NNN.NNN",
"                ",
"        f       ",
"m               ",
"NNN.NNNN.NNN....",
"        f       ",
"               m",
"...NNN.NNNNN.NNN",
"                ",
"m               ",
"XXXXXXXXXXXX....",
"                ",
"        f       ",
"               m",
"....XXXXXXXXXXXX",
"                ",
"        f       ",
"m               ",
"XXXXXXXX   XXXXX",
"        ..      ",
"        bb..    ",
"          bb    ",
"              ..",
"     f        bb",
"           ..   ",
"           bb   ",
"       ..       ",
"       bb       ",
"                ",
"XXXXX           ",
"m           B   ",
"XXXXXXZZZXXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXX . XXXXXXX",
"XXXXXXZZZXXXXXXX",
"                ",
" ..        ..   ",
"XXX        XXX  ",
"      ....      ",
"      XXXX      ",
"                ",
"m    ....      m",
"XXXXX f  XXXXXXX",
"                ",
"       ..       ",
"     XXXX       ",
"g               ",
"XX           XXX",
"                ",
"  t..j..        ",
"XXXXXXXX  XXXXXX",
"XXXXXXXX  XXXXXX",
"XXXXXXXX  XXXXXX",
"XXXXXXXX  XXXXXX"
]

from user35_8l1Rb3xip0_13 import LevelInfo 

level = LevelInfo(
    "The Volcano",
    grid,
    {'g': ((5,50),),
     'j': ((0,1000,1000),),
     'f': (True,False,False,True,False,True,True),
     'B': (1000,500)
    },
    colors = ['#000000'],
    lavaspeed = 0.5,
    complete_color = 'green'
)